# See docs at https://goreleaser.com/customization/build
project_name: gospeak

builds:
  - main: ./cmd/gospeak
    binary: gospeak
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.VERSION=v{{.Version}}

archives:
  - name_template: "{{ .Binary }}.{{ .Os }}-{{ .Arch }}"
    format: binary

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc

brews:
  - name: gospeak
    tap:
      owner: golang-cz
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    #homepage: "https://example.com/"
    description: "gospeak, Golang interface as your schema for client/server communication"
    license: "MIT"
