name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Unit tests
        run: go test ./...
      - name: Test examples
        run: cd ./_examples && go test ./...
      - name: Build
        run: go build ./cmd/gospeak
